CREATE DATABASE CRM;

CREATE TABLE CUSTOMERS(
ID 				INT AUTO_INCREMENT NOT NULL,
FULL_NAME		VARCHAR(100) NOT NULL,
NIC				VARCHAR(12)	UNIQUE NOT NULL,
DOB				DATE NOT NULL,
ADDRESS			TEXT NOT NULL,
PHONE_NO		VARCHAR(10) NOT NULL,
EMAIL			VARCHAR(50) UNIQUE NOT NULL,
ACCOUNT_TYPE	ENUM("SAVINGS","CURRENT","TERM_DEPOSIT") NOT NULL,
BALANCE			DECIMAL(20,2) NOT NULL,
CREATED_AT		TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

CONSTRAINT pk PRIMARY KEY(ID)
);